#!/bin/bash

if [ "$(uname -o)" != "Android" ]; then
  echo "This script is intended for Android only."
  exit 0
fi

if [ "$(whoami)" != "root" ]; then
  echo "Please run the script as root."
  exit 0
fi

configs=(/data/misc/wifi/WifiConfigStore.xml /data/misc/apexdata/com.android.wifi/WifiConfigStore.xml)
found=false

for z in "${configs[@]}"; do
  if [ -f "$z" ]; then
    config="$z"
    found=true
    break
  fi
done

if [ "$found" = false ]; then
  echo "Wi-Fi configuration files not found."
  exit 0
fi

SSID=($(grep 'name="SSID"' "$config" | sed "s/.*>&quot;//;s/&quot;.*//;s/ /-_-/g"))
PSK=($(grep 'name="PreSharedKey"' "$config" | sed "s/.*>&quot;//;s/&quot;.*//;s/ /-_-/g"))

for i in "${!SSID[@]}"; do
  echo -e "${SSID[$i]} : ${PSK[$i]}" | sed "s/-_-/ /g"
done

